### ISSUE TITLE
CAS support and other useful things

### ISSUE THREAD

**Issue by vtolstov** [shafreeck/cetcd#19]
Do you plan add support for CAS and ability to specify prev values for keys/ttl and other stuff?

**Comment by shafreeck** [comment]
@vtolstov All the etcd apis including `CAS`  have been supported. Sorry for the missing documents

**Comment by vtolstov** [comment]
How can I set key with new value providing prev id?
20 нояб. 2015 г. 8:41 пользователь "Shafreeck Sea" notifications@github.com
написал:

**Comment by shafreeck** [comment]
@vtolstov Check about the master branch. There is an api called `cetcd_cmp_and_swap_by_index` .  May be this is what you want ?

**Comment by vtolstov** [comment]
Thanks ! That what i need. May be write comments to code for autogenerating docs?

**Comment by shafreeck** [comment]
@vtolstov  Good suggestion ！ Thanks, I will do it.
