### ISSUE TITLE
watch a key synchronously

### ISSUE THREAD

**Issue by gzliudan** [shafreeck/cetcd#20]
Does cetcd support watch key synchronously? eg: watch the key and don't return until the key is changed, or reach timeout, or stop flag is being set, or network error.

**Comment by shafreeck** [comment]
Yes, The default `cetcd_multi_watch` works synchronously. But there is no way to timedout now . I'd like to add this feature if it is necessary !

**Comment by gzliudan** [comment]
Would you please give some demo codes?
