### ISSUE TITLE
cetcd_parse_response() problem with incoming big data

### ISSUE THREAD

**Issue by rostvel** [shafreeck/cetcd#23]
**Situation**: we try to receive keys from etcd directory by `cetcd_lsdir(...)`, where in directory more than ~200 keys... more specifically, we try to receive some curl data with size > 16KB.
**Problem**: we can`t parce full response of data more then 16 KB, so more than 
~200-220 keys.

**Comment by shafreeck** [comment]
Is there any error message?

**Comment by rostvel** [comment]
No, there no error message. But once I caught "core dumped".
I think: When we receive a large amount of data, then we should not put a sign `parser->st = response_discard_st;` in line 1024 [cetcd.c], because we have not reached the end of json responce (there are only first piece from the responce).
I do not know at the moment how to fix this problem.

**Comment by shafreeck** [comment]
@rostvel Sorry for my late response. I would try to reproduce the bug and see how to solve it.

**Comment by shafreeck** [comment]
@rostvel I do some fixes, can you check if your problem fixed with the latest codes ?

**Comment by rostvel** [comment]
Ok, I will check it.

**Comment by rostvel** [comment]
What do you think about insert some code [**similar** as lines 1094..1100 from cetcd.c]:
    `//release the parser resource`
 `if (watcher->parser.buf) {`
   `sdsfree(watcher->parser.buf);`
`}`
   `if (watcher->parser.json) {`
   `yajl_free(watcher->parser.json);`
   `cetcd_array_destroy(&watcher->parser.ctx.keystack);`
   `cetcd_array_destroy(&watcher->parser.ctx.nodestack);`
   `}`
TO:
[line 315 from cetcd.c] in `cetcd_reap_watchers(...)` function, because we:
1. Receive response for watcher
2. Below [lines 328, 367] we set options for CURL again.
...in order to avoid memory leaks?

**Comment by shafreeck** [comment]
@rostvel Good point ! I'd fix the memory leaks of multi_watch or multi_watch_async. Feel free to send me a PR if you have some solution.

**Comment by shafreeck** [comment]
@rostvel The memory leaks was fixed.  There is still memory leaks using multiple watcher when stop the 
watcher thread. It usually occurs on exit of a process. So it is acceptable so far I think.
