### ISSUE TITLE
example compile fail on ubuntu 14.04

### ISSUE THREAD

**Issue by xiaoyulei** [shafreeck/cetcd#24]
cc -g -O0 -Wall -I ../third-party/build/include  -lcurl -lpthread  cetcd_get.c ../cetcd.c ../cetcd_array.c ../sds/sds.c ../third-party/build/yajl.c.o ../third-party/build/yajl_alloc.c.o ../third-party/build/yajl_buf.c.o ../third-party/build/yajl_encode.c.o ../third-party/build/yajl_gen.c.o ../third-party/build/yajl_lex.c.o ../third-party/build/yajl_parser.c.o ../third-party/build/yajl_tree.c.o ../third-party/build/yajl_version.c.o   -o cetcd_get
/tmp/ccNw5IP7.o: In function `cetcd_client_init':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:58: undefined reference to`curl_global_init'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:64: undefined reference to `curl_easy_init'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:92: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:95: undefined reference to `curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:96: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:98: undefined reference to `curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:99: undefined reference to`curl_easy_setopt'
/tmp/ccNw5IP7.o:/mnt/hdd1/work/cetcd/examples/../cetcd.c:100: more undefined references to `curl_easy_setopt' follow
/tmp/ccNw5IP7.o: In function`cetcd_client_destroy':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:114: undefined reference to `curl_easy_cleanup'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:115: undefined reference to`curl_global_cleanup'
/tmp/ccNw5IP7.o: In function `cetcd_setup_tls':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:165: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:168: undefined reference to `curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:171: undefined reference to`curl_easy_setopt'
/tmp/ccNw5IP7.o: In function `cetcd_watcher_create':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:189: undefined reference to`curl_easy_init'
/tmp/ccNw5IP7.o: In function `cetcd_watcher_release':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:206: undefined reference to`curl_easy_cleanup'
/tmp/ccNw5IP7.o: In function `cetcd_watcher_reset':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:229: undefined reference to`curl_easy_reset'
/tmp/ccNw5IP7.o: In function `cetcd_curl_setopt':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:267: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:272: undefined reference to `curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:274: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:276: undefined reference to `curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:277: undefined reference to`curl_easy_setopt'
/tmp/ccNw5IP7.o:/mnt/hdd1/work/cetcd/examples/../cetcd.c:279: more undefined references to `curl_easy_setopt' follow
/tmp/ccNw5IP7.o: In function`cetcd_reap_watchers':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:350: undefined reference to `curl_easy_getinfo'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:360: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:362: undefined reference to `curl_multi_remove_handle'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:363: undefined reference to`curl_easy_reset'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:365: undefined reference to `curl_multi_add_handle'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:379: undefined reference to`curl_multi_remove_handle'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:392: undefined reference to `curl_multi_remove_handle'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:398: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:401: undefined reference to `curl_multi_add_handle'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:405: undefined reference to`curl_multi_remove_handle'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:347: undefined reference to `curl_multi_info_read'
/tmp/ccNw5IP7.o: In function`cetcd_multi_watch':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:422: undefined reference to `curl_multi_init'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:426: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:427: undefined reference to `curl_multi_add_handle'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:432: undefined reference to`curl_multi_perform'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:438: undefined reference to `curl_multi_timeout'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:445: undefined reference to`curl_multi_fdset'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:450: undefined reference to `curl_multi_perform'
/tmp/ccNw5IP7.o: In function`cetcd_multi_watch_async':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:491: undefined reference to `pthread_create'
/tmp/ccNw5IP7.o: In function`cetcd_multi_watch_async_stop':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:501: undefined reference to `pthread_cancel'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:502: undefined reference to`pthread_join'
/tmp/ccNw5IP7.o: In function `cetcd_send_request':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:1099: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:1100: undefined reference to `curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:1102: undefined reference to`curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:1110: undefined reference to `curl_easy_setopt'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:1113: undefined reference to`curl_easy_setopt'
/tmp/ccNw5IP7.o:/mnt/hdd1/work/cetcd/examples/../cetcd.c:1116: more undefined references to `curl_easy_setopt' follow
/tmp/ccNw5IP7.o: In function`cetcd_send_request':
/mnt/hdd1/work/cetcd/examples/../cetcd.c:1125: undefined reference to `curl_easy_perform'
/mnt/hdd1/work/cetcd/examples/../cetcd.c:1142: undefined reference to`curl_easy_strerror'
collect2: error: ld returned 1 exit status
make: **\* [cetcd_get] Error 1

**Comment by shafreeck** [comment]
`cetcd` depends on the `libcurl` to issue a HTTP request, you should install libcurl first before building cetcd.

**Comment by xiaoyulei** [comment]
@shafreeck yes, I had installed libcurl.

**Comment by shafreeck** [comment]
The errors turn out that it can not find the libcurl library, maybe you should add the path(if you installed) to  
LDFLAGS. Ex:`-L /path/to/your/libcurl`

**Comment by xiaoyulei** [comment]
@shafreeck No, it is different. If it can not find libcurl library, it will report can not find file. But now, it can find the file, but can not find symbol from file.
