### ISSUE TITLE
Can cetcd add/delete watch dynamically?

### ISSUE THREAD

**Issue by xiaoyulei** [shafreeck/cetcd#26]
In example/multi_watch.c, I see the code that initialize count of watchers before watch. But if the watcher and path are dynamic, how to handle it? Do I must `cetcd_multi_watch_async_stop` first,  `cetcd_add_watcher` and `cetcd_multi_watch_async` again?

```
    cetcd_array_init(&watchers, 3);
    cetcd_add_watcher(&watchers, cetcd_watcher_create(&cli, "/test/watch", 0, 1, 1, watch, NULL));
    cetcd_add_watcher(&watchers, cetcd_watcher_create(&cli, "/test/watch", 0, 1, 1, watch, NULL));
    cetcd_add_watcher(&watchers, cetcd_watcher_create(&cli, "/test/watch", 0, 1, 1, watch, NULL));
    wid = cetcd_multi_watch_async(&cli, &watchers);
    while(!quit) {
        usleep(10000);
    }
    cetcd_multi_watch_async_stop(&cli, wid);
```

**Comment by shafreeck** [comment]
You can stop a watcher using `cetcd_stop_watcher`. A stopped watcher will be reaped by `cetcd_reap_watchers`.
