### ISSUE TITLE
free parser.json caused Segmentaion in cetcd_send_request()

### ISSUE THREAD

**Issue by xiaotaoz** [shafreeck/cetcd#29]
In cetcd_send_request(),parser.json wasn't initiated, and it will freed if it's not null.
Normally it’s initiated in callback cetcd_parse_response(), but for failure case( e.g. got 503 response), it also won’t init. So we will free a pointer with garbage data which causes Segmentation.

The fix is: 
init json in cetcd_parse_response() or cetcd_send_request()(preferred).

Code:
void *cetcd_send_request(CURL *curl, cetcd_request *req) {
    cetcd_response_parser parser;
....
    if (parser.json) {
        yajl_free(parser.json);
        cetcd_array_destroy(&parser.ctx.keystack);
        cetcd_array_destroy(&parser.ctx.nodestack);
    }

cetcd_parse_response()
{
            if (ptr[i] == '\n') {
                parser->st = blank_line_st;
                if (parser->http_status >= 300 && parser->http_status < 400) {  //error code is 503 in our run as below log shown
                    /_this is a redirection, restart the state machine_/
                    parser->st = request_line_start_st;
                    break;
                }
                continue;
            }
}

**Comment by xiaotaoz** [comment]
@shafreeck 
add the trace:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff06b85b1 in yajl_free () from /usr/lib64/libyajl.so.2
(gdb) bt
#0  0x00007ffff06b85b1 in yajl_free () from /usr/lib64/libyajl.so.2
#1  0x00007ffff0b2ff2f in cetcd_send_request (curl=0x7fffdc2b19cc, req=0x7fffc7386750) at cetcd.c:1130
        yajl_free(parser.json);
#2  0x00007ffff0b300c5 in cetcd_cluster_request (cli=0x7fffdc2aeecc, req=0x7fffc7386750) at cetcd.c:1166
#3  0x00007ffff0b2e44f in cetcd_set (cli=0x7fffdc2aeecc,
    key=0x7fffc73867b0 "/tas01/service/local/skydns/rf/dtd/stdn", value=0x1009e937 "dtd write ETCD", ttl=0)
    at cetcd.c:543

(gdb) i locals
res = CURLE_OK
parser = {st = 14, http_status = 503, api_type = ETCD_KEYS, buf = 0x7fffdc312414 "", resp = 0x7fffdc2ba94c,
  ctx = {userdata = 0x7fffdc2ba854, keystack = {elem = 0x7fffc7386720, count = 140736887237108,
      cap = 140737351975520}, nodestack = {elem = 0x0, count = 140736887236940, cap = 140736535750256}},
  json = 0x7ffff6c97dea <malloc+26>}
resp = 0x7fffdc2ba94c
addrs = 0x0

**Comment by shafreeck** [comment]
Thanks for your report. It has been fixed now. See #31
