### ISSUE TITLE
etcd_set enhancement 

### ISSUE THREAD

**Issue by janiu-001** [shafreeck/cetcd#32]
Hi, 

The cetcd has two APIs to writ the key/value, cetcd_update and cetcd_set, is it better to add the prevExist in the etcd_set? Then we only use  cetcd_set to create a key, and use cetcd_update to update a key. 

cetcd_response *cetcd_set(cetcd_client *cli, const char *key,
        const char *value, uint64_t ttl) {
    cetcd_request req;
    cetcd_response *resp;
    cetcd_string params;

```
memset(&req, 0, sizeof(cetcd_request));
req.method = ETCD_HTTP_PUT;
req.api_type = ETCD_KEYS;
req.uri = sdscatprintf(sdsempty(), "%s%s", cli->keys_space, key);
params = sdscatprintf(sdsempty(), "value=%s", value);
params = sdscatprintf(sdsempty(), "prevExist=false");
if (ttl) {
    params = sdscatprintf(params, "&ttl=%lu", ttl);
}
req.data = params;
resp = cetcd_cluster_request(cli, &req);
sdsfree(req.uri);
sdsfree(params);
return resp;
```

}

**Comment by janiu-001** [comment]
Hi,

I should make a mistake, the enhancement i suggest  is like: 
    req.uri = sdscatprintf(sdsempty(), "%s%s", cli->keys_space, key);
   params = sdscatprintf(sdsempty(), "value=%s&prevExist=false", value);

Would you share your ideas if it is acceptable? 

Thanks,
Jason

**Comment by shafreeck** [comment]
There is some different with `set` and `update`, `set` can overwrite the key if it is exist and add it otherwise. `update` just update an exist key.
