### ISSUE TITLE
array_index

### ISSUE THREAD

**Issue by kinsu** [shafreeck/cetcd#34]
at cetcd.c during cetcd_del_watcher code checks if index is valid (i,e if if the watcher was deleted before)
318         if (watcher && index > 0)
but as far as i understood index (which is set from cetcd.317 watcher->array_index) can be in zero position. shouldn't this changed to index >= 0 ?

**Comment by shafreeck** [comment]
@kinsu 
Yes, you are right, it is a bug here. Thanks very much for you feedback.

**Comment by kinsu** [comment]
thx for the update!
