### ISSUE TITLE
etcd down notification

### ISSUE THREAD

**Issue by kinsu** [shafreeck/cetcd#35]
In case cetcd_multi_watch_async i sused and at any given point etcd is not reachable anymore, how is application notified ?

From what i saw there is no notification. After etcd is reachable again subscription is renewed but any notification is responced with 
Error Code:1000
Error Message:not a json response
Error Cause:HTTP/1.1 200 OK

thank you

**Comment by kinsu** [comment]
hi again, i think that the problem is that state machine (for parser) is not reset after watch is re-issued after etcd is reachable again. I have created a pull request for a possible fix. 

thank you

**Comment by shafreeck** [comment]
Thanks very much for your contribution. I'd like to test about pr these days.
