### ISSUE TITLE
special character in value will be changed or fail the set command

### ISSUE THREAD

**Issue by zhileitao** [shafreeck/cetcd#38]
Hi Shafreeck, 

I found there is an issue withAPI cetcd_set(). If there is a '+' in the value, it will be replaced to a blank. 

```
cetcd_response *cetcd_set(cetcd_client *cli, const char *key, const char *value, uint64_t ttl)
```

Here is the detailed analysis on this issue and proposed solution. 
### 1) Problem description

For URL, it only allows a-z, A-Z, 0-9, '-', '.', '_' or '~' . For all other characters, it should be converted to their "URL escaped" version (%NN where NN is a two-digit hexadecimal number). 
If without conversion, the set operation will either fail or being changed automatically. The following is the experiment(Note: sdcctl is the command that build with cetcd API, the set operation will call cetcd_set()):

1). The "+" will be automatically change to blank:

```
[root@etcd0-10-135-16-139 sdc]# sdcctl set myKey "plus++plus"
plus  plus
[root@etcd0-10-135-16-139 sdc]# sdcctl get myKey
plus  plus
```

2). It will fail if value has "%". 

```
[root@etcd0-10-135-16-139 sdc]# sdcctl set myKey "plus%%plus"
Error code 210
Error message: Invalid POST form
Error cause: invalid URL escape "%%p"
[root@etcd0-10-135-16-139 sdc]# sdcctl set myKey "plus%plus"
Error code 210
Error message: Invalid POST form
Error cause: invalid URL escape "%pl"
[root@etcd0-10-135-16-139 sdc]#
```
### 2). The proposed solution

One of the easiest solution is to do a conversion by [calling curl_easy_escape](https://curl.haxx.se/libcurl/c/curl_easy_escape.html)( CURL \* curl , const char \* string , int length ). 

the following is example code: 

```
cetcd_response *cetcd_set(cetcd_client *cli, const char *key, const char *value, uint64_t ttl) {
    cetcd_request req;
    cetcd_response *resp;
    cetcd_string params;
    char * value_ptr;

    memset(&req, 0, sizeof(cetcd_request));
    req.method = ETCD_HTTP_PUT;
    req.api_type = ETCD_KEYS;
    req.uri = sdscatprintf(sdsempty(), "%s%s", cli->keys_space, key);
    value_ptr = curl_easy_escape(cli->curl, value, strlen(value));  /* convert the value string */
    params = sdscatprintf(sdsempty(), "value=%s", value_ptr); /* use converted value string */
    if (ttl) {
        params = sdscatprintf(params, "&ttl=%lu", ttl);
    }
    req.data = params;
    resp = cetcd_cluster_request(cli, &req);
    sdsfree(req.uri);
    sdsfree(params);
    curl_free(value_ptr); /* free the memory */
    return resp;
}
```

Besides cetcd_set(), 
- cetcd_update()
- cetcd_create() 
- cetcd_create_in_order()
- cetcd_cmp_and_swap()
- cetcd_cmp_and_swap_by_index() 
  also has the similar issue. 

Do you think we should enhance it? if yes, I will make the changes and send a pull request. @shafreeck 

Regards
Sam

**Comment by shafreeck** [comment]
@zhileitao  Yeah, it's a bug. I am very glad if you send me a pull request !

**Comment by zhileitao** [comment]
Hi Shafreeck,

Thanks for the quick response. I'll make the changes and send you the pull
request.

Regards
Sam

2016-10-28 13:57 GMT+08:00 Shafreeck Sea notifications@github.com:
