### ISSUE TITLE
shall copy the http return code into error code?

### ISSUE THREAD

**Issue by nenzhang** [shafreeck/cetcd#40]
shall copy the http_status into err?

if (parser->http_status != 200 && parser->http_status != 201) {
                    resp->err = calloc(1, sizeof(cetcd_error));
                    parser->ctx.userdata = resp->err;
                    parser->json = yajl_alloc(&error_callbacks, 0, &parser->ctx);

**Comment by shafreeck** [comment]
What do you mean here ?

**Comment by nenzhang** [comment]
Hi Shafreeck
I mean after calloc, the error code in this err is 0 as initialized.
however, in this situation, when http_status is not 200 and 201, it indicates that error happens and need to indicate to upper user to do retry, for example, the PUT request has been delivered failed when etcd instances are down.
